ALTER TABLE user_addresses
ADD COLUMN IF NOT EXISTS latitude NUMERIC(10, 8),
ADD COLUMN IF NOT EXISTS longitude NUMERIC(11, 8);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS ship_latitude NUMERIC(10, 8),
ADD COLUMN IF NOT EXISTS ship_longitude NUMERIC(11, 8);
