spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shopease}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
server:
  port: 8081
management.endpoints.web.exposure.include: health,info


app:
  jwt:
    secret:  ${JWT_SECRET:U7CSWNhO7HE9fSam/uQx2UyK8LyCArTLsCb+2u+W3rA=}   # min 32 bytes for HS256
    access-token-expiry: 900        # 15 minutes
    refresh-token-expiry: 604800    # 7 days
